### ISSUE TITLE
출석 정책 정하기

### ISSUE THREAD

**Issue by belljun3395** [belljun3395/WifiConnectObserver#2]
기존 출석 정책은 아래와 같다.

사용자가 등록한 wifi를 조회한 후 등록한 기기의 MAC 주소가 있으면 출석 인정

**Comment by belljun3395** [comment]
### 출석 정책

우선 출석의 경우 등록된 기기의 **Wifi 접속 기록을 기반**한다.

출석의 경우 **09시를 기**준으로 한다.

접속 기록이 많다고 하더라도 최초 접속 기록을 기준으로 **하루에 접속은 하나만 인정된다.**

즉 09시 접속 기록과 10시 접속 기록이 있더라도 출석은 하나로 인정된다.

**Comment by mtak0235** [comment]
# 상황
동방 wifi의 망을 사용하는 사용자의 기기가 받는 사설 Ip는 임대 시간에 따라 바뀌기도 하는 동적 ip라고 알고 있습니다.
이후 접속한 IP와 비교해서 출석 기능을 수행할 떄 제대로 매치가 안될 수도 있다고 생각합니다.
# 원인 분석
디비에 저장된 기기의 식별 기준이 정적 정보(ex. mac) 가 아닌 동적 정보(ip)이기 때문입니다.
# 제안
식별 기준을 MAC으로 하는건 어떨까요?
MAC으로 바꿀 시, 다양한 wifi기기를 대상으로 출석 데이터를 수집할 떄도 등록된 다른 사용자의 사설 Ip주소와 겹치는 일을 막을 수 있을 것 같습니다.

**Comment by belljun3395** [comment]
> 등록한 ip 주소와 접속한 ip 주소가 동일하면 출석을 인정

이 부분은 제가 작성을 잘못하였네요!
**사용자가 등록한 wifi를 조회한 후 등록한 기기의 MAC 주소가 있으면 출석 인정**으로 수정하겠습니다!

그리고 **wifi ip 자체가 동적인 경우**도 생각해봐야겠네요
서비스 사전조건에 "wifi ip를 고정으로 바꿔야 한다" 이런 조건과 방법을 추가해서요

**Comment by mtak0235** [comment]
Wifi ip를 고정으로 바꾸면 비용이 발생하는것으로 알고 있습니다. 기기를 식별하는 고정 정보를 수집하는 방향으로 조사해보는게 어떨까요?

**Comment by belljun3395** [comment]
아하 그렇군요..
iptime의 경우 ip 고정에 대한 비용이 따로 없었던것 같은데 
이부분에 대해서는 조금더 조사가 필요하겠네요!

**Comment by belljun3395** [comment]
#25 하나의 wifi에 연결된 상태로 24시간이 넘어갈 경우

**Comment by belljun3395** [comment]
출석 정책은 기획 변경에 따라 폐기
