### ISSUE TITLE
[회의록] 6월 9일

### ISSUE THREAD

**Issue by belljun3395** [belljun3395/WifiConnectObserver#60]
### 요구 사항 
[링크](https://github.com/belljun3395/WifiConnectObserver/issues?q=is%3Aopen+is%3Aissue+label%3AAPI)와 같이 할 수 있을 것 같음

### 계획 
파트별 계획과 공통 계획이 필요할 것이라 생각

#### 공통 계획
테스트 코드 : 
최대한 많은 커버리지를 검증할 수 있었으면 좋겠음(80%, 소나큐브를 통해 확인)

코드 스멜:
ex) 코드 스멜 10개 이상 만들지 말기

문서화 : 
컨트롤러 테스트를 통한 문서화 도입 
공통 개발 스타일 합의 부분 기록(ex: usecase에는 메서드명을 execute로 통일한다.)
엔티티 기록(개발에 필요한 엔티티가 생기면 "이슈"를 통해 요청 -> 리뷰 후 특정 브렌치(ex: entity)에서 작업한 머지하여 사용)
주석(인터페이스 및 주석이 필요한 경우)
공통 자원(aws, sonar)

#### 파트별 계획
현재 크게 프로젝트를 파트로 나누자면 다음과 같음
1. 와이파이 공유기에 접속하여 정보를 조회하는 기능
2. 조회한 정보를 바탕으로 통계
3. 기본적인 CRUD

각 부분의 포인트를 잡자면 다음과 같음
1번 : 외부 서비스와 연동(와이파이 공유기), 멀티 스레드(반복적인 조회), 확장 가능성
2번 : 통계 구현, 구체적인 정책 적용
3번 : CRUD 구현

### 용어 사전
한번은 정리할 필요가 있을 듯

### 커밋, PR 컨벤션
용어사전이 커밋 컨벤션에도 필요할 것 같음

### 커밋
CherryPick 활용하면 깔끔히 할 수 있기는 한데 적용할 것인지?

### 공유
개발은 각자하지만 개발하면서 공부한 것을 공유할 수 있는 방법 고민할 필요

### 목표
스프링이 도구에 불과하다면 스프링을 사용하지 않을 경우에도 필요한 것에 집중해보자?!

**Comment by belljun3395** [comment]
코드 스타일 관련 설득 시간 가지기

**Comment by belljun3395** [comment]
엔티티 논의 @kssumin  @taeyeon0721 후 확정

**Comment by belljun3395** [comment]
상황에 따른 커밋 규칙 정하기 / 한번에 다 할 수는 없으니 필요하면 이슈를 통해 논의

**Comment by kssumin** [comment]
| 주석
주석만으로도 이해 가능한 코드가 좋은 것이다.

그래서 주석의 범위가 애매하다.

우선은 주석을 달고 해당 부분은 주석이 필요할 것 같아요! 라고 comment를 담기

**Comment by kssumin** [comment]
| PR merge
* sona 큐브 통과
* 2명 approve 후 merge

**Comment by kssumin** [comment]
| 다음 일정
6월 21일 13시

**Comment by belljun3395** [comment]
목요일 저녁시간을 회의및 질문시간으로 가지기
